// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMcD_GlQIuA2Xz97QKdcCEDViWh9pZeT0',
    appId: '1:157413340088:web:02127b4f2b9aef768a154d',
    messagingSenderId: '157413340088',
    projectId: 'health-connect-1d8e4',
    authDomain: 'health-connect-1d8e4.firebaseapp.com',
    storageBucket: 'health-connect-1d8e4.firebasestorage.app',
    measurementId: 'G-TGHHCE4RHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR5I8gcBeQyVHaCqrDx4z6E83fC7splJs',
    appId: '1:157413340088:android:35dd2bc6a5fe447e8a154d',
    messagingSenderId: '157413340088',
    projectId: 'health-connect-1d8e4',
    storageBucket: 'health-connect-1d8e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3K2RGsR90rz4l1yUkjhtug7sbJelwR28',
    appId: '1:157413340088:ios:a3bdf7177b4f2e968a154d',
    messagingSenderId: '157413340088',
    projectId: 'health-connect-1d8e4',
    storageBucket: 'health-connect-1d8e4.firebasestorage.app',
    iosBundleId: 'com.gotg.healthConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3K2RGsR90rz4l1yUkjhtug7sbJelwR28',
    appId: '1:157413340088:ios:a3bdf7177b4f2e968a154d',
    messagingSenderId: '157413340088',
    projectId: 'health-connect-1d8e4',
    storageBucket: 'health-connect-1d8e4.firebasestorage.app',
    iosBundleId: 'com.gotg.healthConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMcD_GlQIuA2Xz97QKdcCEDViWh9pZeT0',
    appId: '1:157413340088:web:99855a0e0c40e8c78a154d',
    messagingSenderId: '157413340088',
    projectId: 'health-connect-1d8e4',
    authDomain: 'health-connect-1d8e4.firebaseapp.com',
    storageBucket: 'health-connect-1d8e4.firebasestorage.app',
    measurementId: 'G-P2ER4XTDL6',
  );
}
